name: src
description: "Proyecto Flutter - Catálogo de Películas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Peticiones HTTP
  http: ^1.1.0

  # (Para la unidad de Firebase, lo dejamos ya agregado)
  firebase_core: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de estilo recomendadas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_background.jpg
